name: super_material
description: 'Allows easy switching between multiple designs at runtime. Material and cupertino are currently supported.'
version: 0.0.2
repository: 'https://github.com/MarchMore/super_material'

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.17.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4