name: super_material
description: 'Allows easy switching between multiple designs at runtime. Material and cupertino are currently supported.'
version: 0.0.1
repository: 'https://github.com/MarchMore/super_material'

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4